import streamlit as st
import requests
import io
from PIL import Image

st.set_page_config(page_title="Nexus Flow AI", page_icon="⚡", layout="wide")

# Custom CSS
st.markdown("""
    <style>
    .stChatMessage { border-radius: 15px; margin-bottom: 10px; }
    .stChatInputContainer { padding-bottom: 20px; }
    .main { background-color: white; color: black; }
    </style>
    """, unsafe_allow_html=True)

st.title("Nexus Flow AI ⚡")
st.caption("Advanced Assistant for Coding, SAT, BSEB & Images")

if "messages" not in st.session_state:
    st.session_state.messages = []

# Display History
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

# Chat Processor
if prompt := st.chat_input("How can Nexus help you today?"):
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    # Railway Backend URL
    backend_url = "https://web-production-68d0e.up.railway.app/ask" 
    
    with st.chat_message("assistant"):
        with st.spinner("Nexus is processing..."):
            try:
                response = requests.post(
                    backend_url, 
                    json={"user_input": prompt},
                    timeout=60 # Reduced timeout for better UX
                )
                
                if response.status_code == 200:
                    answer = response.json().get("response")
                    st.markdown(answer)
                    st.session_state.messages.append({"role": "assistant", "content": answer})
                else:
                    st.error(f"Engine Error: {response.json().get('detail', 'Unknown error')}")
            except Exception as e:
                st.error(f"Connection Failed: Ensure Railway is ACTIVE.")

# Sidebar
with st.sidebar:
    st.title("🛡️ Nexus Control")
    if st.button("🗑️ Clear Chat"):
        st.session_state.messages = []
        st.rerun()
    
    st.write("---")
    st.subheader("🎨 Image Generator")
    img_prompt = st.text_input("Enter prompt:")
    if st.button("Generate"):
        if img_prompt:
            with st.spinner("Drawing..."):
                try:
                    res = requests.post(
                        "https://web-production-68d0e.up.railway.app/generate-image",
                        json={"image_prompt": img_prompt},
                        timeout=120
                    )
                    if res.status_code == 200:
                        st.image(res.content, caption="Generated by Nexus")
                    else:
                        st.error("Model is waking up. Try again in a moment.")
                except Exception as e:
                    st.error("Image Service Offline.")
                    
